#!/bin/bash
echo Building...
./gradlew build -q

count=$1

function clean_up {
	if [[ count -eq 2 ]]; then
		kill -9 $pid1
		kill -9 $pid2
	else
                kill -9 $pid1
                kill -9 $pid2
		kill -9 $pid3
		kill -9 $pid4
	fi
}


if [[ count -eq 2 ]]; then
        echo Starting up two Servers
	java -cp build/libs/quoridorFE.jar quoridorFE.Server --port 9999 &
	pid1=$!
	java -cp build/libs/quoridorFE.jar quoridorFE.Server --port 8888 &
        pid2=$!

	echo Starting up viewer
	java -cp build/libs/quoridorFE.jar quoridorFE.Client localhost:9999 localhost:8888

	echo Happy Hacking~
else
        echo Starting up four Servers
        java -cp build/libs/quoridorFE.jar quoridorFE.Server --port 9999 &
        pid1=$!

        java -cp build/libs/quoridorFE.jar quoridorFE.Server --port 8888 &
        pid2=$!

        java -cp build/libs/quoridorFE.jar quoridorFE.Server --port 7777 &
        pid3=$!

        java -cp build/libs/quoridorFE.jar quoridorFE.Server --port 6666 &
        pid4=$!

        echo Starting up viewer
        java -cp build/libs/quoridorFE.jar quoridorFE.Client localhost:9999 localhost:8888 localhost:7777 localhost:6666

	echo Happy Hacking~
fi

clean_up
exit 0
